// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfig) DeepCopyInto(out *TFConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfig.
func (in *TFConfig) DeepCopy() *TFConfig {
	if in == nil {
		return nil
	}
	out := new(TFConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TFConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigAPISpec) DeepCopyInto(out *TFConfigAPISpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigAPISpec.
func (in *TFConfigAPISpec) DeepCopy() *TFConfigAPISpec {
	if in == nil {
		return nil
	}
	out := new(TFConfigAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigDeviceMgr) DeepCopyInto(out *TFConfigDeviceMgr) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigDeviceMgr.
func (in *TFConfigDeviceMgr) DeepCopy() *TFConfigDeviceMgr {
	if in == nil {
		return nil
	}
	out := new(TFConfigDeviceMgr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigList) DeepCopyInto(out *TFConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TFConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigList.
func (in *TFConfigList) DeepCopy() *TFConfigList {
	if in == nil {
		return nil
	}
	out := new(TFConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TFConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigSVCMonitorSpec) DeepCopyInto(out *TFConfigSVCMonitorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigSVCMonitorSpec.
func (in *TFConfigSVCMonitorSpec) DeepCopy() *TFConfigSVCMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(TFConfigSVCMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigSchemaSpec) DeepCopyInto(out *TFConfigSchemaSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigSchemaSpec.
func (in *TFConfigSchemaSpec) DeepCopy() *TFConfigSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(TFConfigSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigSpec) DeepCopyInto(out *TFConfigSpec) {
	*out = *in
	in.APISpec.DeepCopyInto(&out.APISpec)
	in.SVCMonitorSpec.DeepCopyInto(&out.SVCMonitorSpec)
	in.SchemaSpec.DeepCopyInto(&out.SchemaSpec)
	in.DeviceMgrSpec.DeepCopyInto(&out.DeviceMgrSpec)
	if in.CofigMapList != nil {
		in, out := &in.CofigMapList, &out.CofigMapList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigSpec.
func (in *TFConfigSpec) DeepCopy() *TFConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TFConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TFConfigStatus) DeepCopyInto(out *TFConfigStatus) {
	*out = *in
	if in.ConfigMapList != nil {
		in, out := &in.ConfigMapList, &out.ConfigMapList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TFConfigStatus.
func (in *TFConfigStatus) DeepCopy() *TFConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TFConfigStatus)
	in.DeepCopyInto(out)
	return out
}
