apiVersion: config.tf.mirantis.com/v1alpha1
kind: TFConfig
metadata:
  name: tfconfig-api
spec:
  configmaps: 
    - tf-rabbitmq-cfgmap
  api:
    replicas: 1
    image: willco/opencontrail-config-api:r5.1
    ports:
      - name: api
        port: 9100
      - name: introspect
        port: 8084
    env:
      - name: TF_SANDESH_SEND_RATE_LIMIT
        value: 100

  svc-monitor:
    replicas: 1
    image: willco/opencontrail-config-svc-monitor:r5.1
    ports:
      - name: introspect
        port: 8088

  schema:
    replicas: 1
    image: willco/opencontrail-config-schema:r5.1

  devicemgr:
    replicas: 1
    image: willco/opencontrail-config-devicemgr:r5.1
    ports:
      - name: introspect
        port: 8087
